# Generated by Django 4.0.3 on 2022-06-02 00:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.BooleanField(verbose_name=True)),
                ('phoneNum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('weight', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
            ],
        ),
    ]
