# Generated by Django 4.0.3 on 2022-06-18 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_feed_record_feed_recordids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='recordIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=100),
        ),
    ]
