# Generated by Django 4.0.3 on 2022-06-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0002_profile_delete_userpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
